apiVersion: apps/v1
kind: Deployment
metadata:
  name: procesa-pago-deployment
  labels:
    app: procesa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: procesa-pago
  template:
    metadata:
      labels:
        app: procesa-pago
    spec:
      containers:
        - name: procesa-pago
          image: procesa-pago:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
